apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins
  namespace: jenkins
data:
    values.yaml: |-
      controller:
        jenkinsUrl: https://jenkins.markguiang.dev
        additionalExistingSecrets: 
          - name: jenkins-credentials-icy
            keyName: user-username-icy
          - name: jenkins-credentials-icy
            keyName: user-password-icy
        JCasC:
          securityRealm: |-
            local:
              users:
                - id: "${chart-admin-username}"
                  name: "Jenkins Admin"
                  password: "${chart-admin-password}"
                - id: "${user-username-icy}"
                  name: "${user-username-icy} account"
                  password: "${user-password-icy}"

