apiVersion: v1
kind: Namespace
metadata:
  name: jenkins 
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 24h 
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 1h
  chart:
    spec:
      chart: jenkins
      version: '4.3.30'
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
  values:
    controller:
      ingress:
        enabled: true
        apiVersion: networking.k8s.io/v1
        path: /jenkins
    
