apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yaml
  - jenkins.yaml
  - cert-manager.yaml
  - sealed-secrets.yaml
  - secret-replicator.yaml
spec:
  timeout: 5m0s
  interval: 10m0s
