apiVersion: v1
kind: Namespace
metadata:
  name: secret-replicator
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kiwigrid
  namespace: flux-system
spec:
  interval: 15m
  url: https://kiwigrid.github.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-replicator
  namespace: secret-replicator
spec:
  chart:
    spec:
      chart: secret-replicator
      version: 0.6.x
      sourceRef:
        kind: HelmRepository
        name: kiwigrid
        namespace: flux-system
  interval: 10m
  timeout: 5m
  values:
    secretList: "letsencrypt"
    secretNamespace: "letsencrypt"
