apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base/podinfo
  - ../base/shop
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
