apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-values
  namespace: jenkins
data:
    values.yaml: |-
      controller:
        jenkinsUrl: https://jenkins.markguiang.dev
        additionalPlugins:
          - github:1.37.3
        additionalExistingSecrets: 
          - name: jenkins-credentials-icy
            keyName: username
          - name: jenkins-credentials-icy
            keyName: password
        JCasC:
          securityRealm: |-
            local:
              users:
                - id: "${chart-admin-username}"
                  name: "Jenkins Admin"
                  password: "${chart-admin-password}"
                - id: "${jenkins-credentials-icy-username}"
                  name: "${jenkins-credentials-icy-username} account"
                  password: "${jenkins-credentials-icy-password}"

