apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-values
  namespace: jenkins
data:
    values.yaml: |-
      controller:
        jenkinsUrl: https://jenkins.markguiang.dev
        installPlugins:
          - kubernetes:3937.vd7b_82db_e347b_
          - workflow-aggregator:596.v8c21c963d92d
          - git:5.2.0
          - configuration-as-code:1647.ve39ca_b_829b_42
          - github:1.37.3
          - job-dsl:1.84
        additionalExistingSecrets: 
          - name: jenkins-credentials-icy
            keyName: username
          - name: jenkins-credentials-icy
            keyName: password
        JCasC:
          jobs:
            - script: >
              job('seed-job') {
                  scm {
                      github('mark-icy/ci-jobs')
                  }
                  steps {
                      dsl {
                          // Fetch all .groovy files in the repository and process them
                          def groovyFiles = findFiles { it.endsWith('.groovy') }
                          groovyFiles.each { file ->
                              external(file)
                          }
                      }
                  }
              }
          securityRealm: |-
            local:
              users:
                - id: "${chart-admin-username}"
                  name: "Jenkins Admin"
                  password: "${chart-admin-password}"
                - id: "${jenkins-credentials-icy-username}"
                  name: "${jenkins-credentials-icy-username} account"
                  password: "${jenkins-credentials-icy-password}"

