apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-values
  namespace: jenkins
data:
  values.yaml: |-
    controller:
      jenkinsUrl: https://jenkins.markguiang.dev
      installPlugins:
        - kubernetes:3985.vd26d77b_2a_48a_
        - workflow-aggregator:596.v8c21c963d92d
        - git:5.2.0
        - configuration-as-code:1670.v564dc8b_982d0
        - github:1.37.3
        - job-dsl:1.84
        - javax-mail-api:1.6.2-9
        - pipeline-utility-steps:2.16.0
      additionalExistingSecrets:
        - name: jenkins-credentials-icy
          keyName: username
        - name: jenkins-credentials-icy
          keyName: password
      JCasC:
        configScripts:
          seed-jobs: |
            security:
              globalJobDslSecurityConfiguration:
                useScriptSecurity: false
            jobs:
              - script: >
                  job('seed-job') {
                    scm {
                      github('mark-icy/ci-jobs')
                    }
                    steps {
                      dsl {
                        external('hello.groovy')
                        removeAction('DELETE')
                      }
                    }
                  }
              - script: >
                pipelineJob('seed-job') {
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url('https://github.com/mark-icy/ci-jobs.git')
                          }
                          branch('main')
                        }
                      }
                      scriptPath('./seed-job/Jenkinsfile')
                    }
                  }
                }
        securityRealm: |-
          local:
            users:
              - id: "${chart-admin-username}"
                name: "Jenkins Admin"
                password: "${chart-admin-password}"
              - id: "${jenkins-credentials-icy-username}"
                name: "${jenkins-credentials-icy-username} account"
                password: "${jenkins-credentials-icy-password}"
