apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-values
  namespace: jenkins
data:
    values.yaml: |-
      controller:
        jenkinsUrl: https://jenkins.markguiang.dev
        installPlugins:
          - kubernetes:3937.vd7b_82db_e347b_
          - workflow-aggregator:596.v8c21c963d92d
          - git:5.2.0
          - configuration-as-code:1647.ve39ca_b_829b_42
          - github:1.37.3
        additionalExistingSecrets: 
          - name: jenkins-credentials-icy
            keyName: username
          - name: jenkins-credentials-icy
            keyName: password
        JCasC:
          securityRealm: |-
            local:
              users:
                - id: "${chart-admin-username}"
                  name: "Jenkins Admin"
                  password: "${chart-admin-password}"
                - id: "${jenkins-credentials-icy-username}"
                  name: "${jenkins-credentials-icy-username} account"
                  password: "${jenkins-credentials-icy-password}"

