apiVersion: v1
kind: Namespace
metadata:
  name: mc
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mc
  namespace: flux-system
spec:
  interval: 5m
  url: https://itzg.github.io/minecraft-server-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc
  namespace: mc
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: mc
        namespace: flux-system
  values:
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      paperDownloadUrl: "https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/159/downloads/paper-1.20.1-159.jar"
      difficulty: normal
      allowNether: true
      downloadWorldUrl: "https://www.dropbox.com/scl/fi/m0om5352qfj0gjhbbk3qf/world.zip?rlkey=s86fbp37175iq2bk1qlp8p04m&dl=1"
      removeOldMods: true
      onlineMode: false
      enforceSecureProfile: false
      serviceType: LoadBalancer
      memory: 2048M
